apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-service
  labels:
    app: my-app-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app-service
  template:
    metadata:
      labels:
        app: my-app-service
    spec:
      containers:
      - name: my-app-service
        image: 192.168.214.152/cp/my-app:0.0.1-SNAPSHOT
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8096
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  labels:
    app: my-app-service
spec:
  ports:
    - port: 8096
      targetPort: 8096
      nodePort: 30206
  selector:
    app: my-app-service
  type: NodePort
